// 150 Most Important Stocks for Real-time Market Data
// Enhanced with comprehensive trader-friendly fields for TradeX Backend System
// This list includes major indices, blue-chip stocks, and actively traded securities

export interface IStockData {
  symbol: string;
  instrumentToken: string;
  exchangeToken: string;
  exchange: string;
  segment: string;
  type: string;
  priority: number;
  name?: string;
  sector?: string;
  lotSize?: number;
  tickSize?: number;
  avgVolume?: number;
  marketCap?: number;
  isActive?: boolean;
}

export const IMPORTANT_STOCKS: IStockData[] = [
  // Major Indices
  { 
    symbol: 'NIFTY 50', 
    instrumentToken: '256265', 
    exchangeToken: '256265', 
    exchange: 'NSE', 
    segment: 'INDICES', 
    type: 'INDEX', 
    priority: 1,
    name: 'NIFTY 50 Index',
    sector: 'INDEX',
    lotSize: 50,
    tickSize: 0.05,
    avgVolume: 0,
    marketCap: 0,
    isActive: true
  },
  { 
    symbol: 'NIFTY BANK', 
    instrumentToken: '260105', 
    exchangeToken: '260105', 
    exchange: 'NSE', 
    segment: 'INDICES', 
    type: 'INDEX', 
    priority: 2,
    name: 'NIFTY Bank Index',
    sector: 'INDEX',
    lotSize: 25,
    tickSize: 0.05,
    avgVolume: 0,
    marketCap: 0,
    isActive: true
  },
  { 
    symbol: 'SENSEX', 
    instrumentToken: '265', 
    exchangeToken: '265', 
    exchange: 'BSE', 
    segment: 'INDICES', 
    type: 'INDEX', 
    priority: 3,
    name: 'BSE SENSEX',
    sector: 'INDEX',
    lotSize: 10,
    tickSize: 0.05,
    avgVolume: 0,
    marketCap: 0,
    isActive: true
  },
  { 
    symbol: 'NIFTY IT', 
    instrumentToken: '257801', 
    exchangeToken: '257801', 
    exchange: 'NSE', 
    segment: 'INDICES', 
    type: 'INDEX', 
    priority: 4,
    name: 'NIFTY IT Index',
    sector: 'INDEX',
    lotSize: 50,
    tickSize: 0.05,
    avgVolume: 0,
    marketCap: 0,
    isActive: true
  },
  { 
    symbol: 'NIFTY AUTO', 
    instrumentToken: '257545', 
    exchangeToken: '257545', 
    exchange: 'NSE', 
    segment: 'INDICES', 
    type: 'INDEX', 
    priority: 5,
    name: 'NIFTY Auto Index',
    sector: 'INDEX',
    lotSize: 50,
    tickSize: 0.05,
    avgVolume: 0,
    marketCap: 0,
    isActive: true
  },

  // Top Banking Stocks
  { 
    symbol: 'HDFCBANK', 
    instrumentToken: '1333', 
    exchangeToken: '1333', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 6,
    name: 'HDFC Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 25000000,
    marketCap: 1200000,
    isActive: true
  },
  { 
    symbol: 'ICICIBANK', 
    instrumentToken: '1270', 
    exchangeToken: '1270', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 7,
    name: 'ICICI Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 18000000,
    marketCap: 850000,
    isActive: true
  },
  { 
    symbol: 'KOTAKBANK', 
    instrumentToken: '492033', 
    exchangeToken: '1922', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 8,
    name: 'Kotak Mahindra Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8000000,
    marketCap: 380000,
    isActive: true
  },
  { 
    symbol: 'SBIN', 
    instrumentToken: '3045', 
    exchangeToken: '3045', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 9,
    name: 'State Bank of India',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 45000000,
    marketCap: 650000,
    isActive: true
  },
  { 
    symbol: 'AXISBANK', 
    instrumentToken: '5900', 
    exchangeToken: '1594', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 10,
    name: 'Axis Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 22000000,
    marketCap: 380000,
    isActive: true
  },

  // IT Giants
  { 
    symbol: 'TCS', 
    instrumentToken: '2953', 
    exchangeToken: '2953', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 11,
    name: 'Tata Consultancy Services Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8000000,
    marketCap: 1500000,
    isActive: true
  },
  { 
    symbol: 'INFY', 
    instrumentToken: '408065', 
    exchangeToken: '1594', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 12,
    name: 'Infosys Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 750000,
    isActive: true
  },
  { 
    symbol: 'WIPRO', 
    instrumentToken: '3787', 
    exchangeToken: '3787', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 13,
    name: 'Wipro Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 18000000,
    marketCap: 320000,
    isActive: true
  },
  { 
    symbol: 'HCLTECH', 
    instrumentToken: '1850', 
    exchangeToken: '1850', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 14,
    name: 'HCL Technologies Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 10000000,
    marketCap: 450000,
    isActive: true
  },
  { 
    symbol: 'TECHM', 
    instrumentToken: '3465', 
    exchangeToken: '3465', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 15,
    name: 'Tech Mahindra Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 7000000,
    marketCap: 160000,
    isActive: true
  },

  // FMCG Majors
  { 
    symbol: 'HINDUNILVR', 
    instrumentToken: '356865', 
    exchangeToken: '1394', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 16,
    name: 'Hindustan Unilever Limited',
    sector: 'FMCG',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 5000000,
    marketCap: 620000,
    isActive: true
  },
  { 
    symbol: 'ITC', 
    instrumentToken: '424961', 
    exchangeToken: '1660', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 17,
    name: 'ITC Limited',
    sector: 'FMCG',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 28000000,
    marketCap: 550000,
    isActive: true
  },
  { 
    symbol: 'NESTLEIND', 
    instrumentToken: '4598529', 
    exchangeToken: '17963', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 18,
    name: 'Nestle India Limited',
    sector: 'FMCG',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 220000,
    isActive: true
  },
  { 
    symbol: 'BRITANNIA', 
    instrumentToken: '140033', 
    exchangeToken: '547', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 19,
    name: 'Britannia Industries Limited',
    sector: 'FMCG',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 140000,
    isActive: true
  },
  { 
    symbol: 'DABUR', 
    instrumentToken: '197633', 
    exchangeToken: '772', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 20,
    name: 'Dabur India Limited',
    sector: 'FMCG',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 105000,
    isActive: true
  },

  // Auto Sector
  { 
    symbol: 'MARUTI', 
    instrumentToken: '2278657', 
    exchangeToken: '8908', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 21,
    name: 'Maruti Suzuki India Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2800000,
    marketCap: 410000,
    isActive: true
  },
  { 
    symbol: 'TATAMOTORS', 
    instrumentToken: '884737', 
    exchangeToken: '3456', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 22,
    name: 'Tata Motors Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 35000000,
    marketCap: 280000,
    isActive: true
  },
  { 
    symbol: 'M&M', 
    instrumentToken: '519937', 
    exchangeToken: '2031', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 23,
    name: 'Mahindra & Mahindra Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8000000,
    marketCap: 340000,
    isActive: true
  },
  { 
    symbol: 'BAJAJ-AUTO', 
    instrumentToken: '4267265', 
    exchangeToken: '16669', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 24,
    name: 'Bajaj Auto Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1800000,
    marketCap: 240000,
    isActive: true
  },
  { 
    symbol: 'EICHERMOT', 
    instrumentToken: '232961', 
    exchangeToken: '910', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 25,
    name: 'Eicher Motors Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 120000,
    isActive: true
  },

  // Telecom & Energy
  { 
    symbol: 'BHARTIARTL', 
    instrumentToken: '2714625', 
    exchangeToken: '10604', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 26,
    name: 'Bharti Airtel Limited',
    sector: 'TELECOM',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 15000000,
    marketCap: 450000,
    isActive: true
  },
  { 
    symbol: 'RELIANCE', 
    instrumentToken: '738561', 
    exchangeToken: '2885', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 27,
    name: 'Reliance Industries Limited',
    sector: 'ENERGY',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 22000000,
    marketCap: 2000000,
    isActive: true
  },

  // Pharma
  { 
    symbol: 'SUNPHARMA', 
    instrumentToken: '3150849', 
    exchangeToken: '12309', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 28,
    name: 'Sun Pharmaceutical Industries Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8000000,
    marketCap: 280000,
    isActive: true
  },
  { 
    symbol: 'DRREDDY', 
    instrumentToken: '225537', 
    exchangeToken: '881', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 29,
    name: 'Dr. Reddys Laboratories Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2500000,
    marketCap: 110000,
    isActive: true
  },
  { 
    symbol: 'CIPLA', 
    instrumentToken: '177665', 
    exchangeToken: '694', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 30,
    name: 'Cipla Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4500000,
    marketCap: 95000,
    isActive: true
  },

  // Metals & Mining
  { 
    symbol: 'TATASTEEL', 
    instrumentToken: '895745', 
    exchangeToken: '3499', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 31,
    name: 'Tata Steel Limited',
    sector: 'METALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 25000000,
    marketCap: 180000,
    isActive: true
  },
  { 
    symbol: 'JSWSTEEL', 
    instrumentToken: '3001089', 
    exchangeToken: '11723', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 32,
    name: 'JSW Steel Limited',
    sector: 'METALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 18000000,
    marketCap: 220000,
    isActive: true
  },
  { 
    symbol: 'HINDALCO', 
    instrumentToken: '348929', 
    exchangeToken: '1363', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 33,
    name: 'Hindalco Industries Limited',
    sector: 'METALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 140000,
    isActive: true
  },

  // Oil & Gas
  { 
    symbol: 'ONGC', 
    instrumentToken: '633601', 
    exchangeToken: '2475', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 34,
    name: 'Oil and Natural Gas Corporation Limited',
    sector: 'OIL_GAS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 35000000,
    marketCap: 320000,
    isActive: true
  },
  { 
    symbol: 'IOC', 
    instrumentToken: '415745', 
    exchangeToken: '1624', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 35,
    name: 'Indian Oil Corporation Limited',
    sector: 'OIL_GAS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 28000000,
    marketCap: 180000,
    isActive: true
  },

  // Power & Energy
  { 
    symbol: 'POWERGRID', 
    instrumentToken: '3834113', 
    exchangeToken: '14977', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 36,
    name: 'Power Grid Corporation of India Limited',
    sector: 'POWER',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 20000000,
    marketCap: 450000,
    isActive: true
  },
  { 
    symbol: 'NTPC', 
    instrumentToken: '2977281', 
    exchangeToken: '11630', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 37,
    name: 'NTPC Limited',
    sector: 'POWER',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 45000000,
    marketCap: 680000,
    isActive: true
  },

  // Cement
  { 
    symbol: 'ULTRACEMCO', 
    instrumentToken: '2952193', 
    exchangeToken: '11531', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 38,
    name: 'UltraTech Cement Limited',
    sector: 'CEMENT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1500000,
    marketCap: 320000,
    isActive: true
  },
  { 
    symbol: 'SHREECEM', 
    instrumentToken: '556289', 
    exchangeToken: '2174', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 39,
    name: 'Shree Cement Limited',
    sector: 'CEMENT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 200000,
    marketCap: 95000,
    isActive: true
  },

  // Infrastructure
  { 
    symbol: 'LT', 
    instrumentToken: '2939649', 
    exchangeToken: '11483', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 40,
    name: 'Larsen & Toubro Limited',
    sector: 'INFRASTRUCTURE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 5000000,
    marketCap: 420000,
    isActive: true
  },
  { 
    symbol: 'SIEMENS', 
    instrumentToken: '887553', 
    exchangeToken: '3469', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 41,
    name: 'Siemens Limited',
    sector: 'INFRASTRUCTURE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 210000,
    isActive: true
  },

  // NBFCs
  { 
    symbol: 'BAJFINANCE', 
    instrumentToken: '81153', 
    exchangeToken: '317', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 42,
    name: 'Bajaj Finance Limited',
    sector: 'NBFC',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4000000,
    marketCap: 520000,
    isActive: true
  },
  { 
    symbol: 'BAJAJFINSV', 
    instrumentToken: '4268801', 
    exchangeToken: '16675', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 43,
    name: 'Bajaj Finserv Limited',
    sector: 'NBFC',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 220000,
    isActive: true
  },

  // Additional Banking
  { 
    symbol: 'INDUSINDBK', 
    instrumentToken: '1346', 
    exchangeToken: '1346', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 44,
    name: 'IndusInd Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 120000,
    isActive: true
  },
  { 
    symbol: 'BANDHANBNK', 
    instrumentToken: '2263', 
    exchangeToken: '2263', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 45,
    name: 'Bandhan Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 15000000,
    marketCap: 45000,
    isActive: true
  },

  // Consumer Goods
  { 
    symbol: 'TITAN', 
    instrumentToken: '897537', 
    exchangeToken: '3506', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 46,
    name: 'Titan Company Limited',
    sector: 'CONSUMER_GOODS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 320000,
    isActive: true
  },
  { 
    symbol: 'ASIANPAINT', 
    instrumentToken: '60417', 
    exchangeToken: '236', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 47,
    name: 'Asian Paints Limited',
    sector: 'CONSUMER_GOODS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2800000,
    marketCap: 340000,
    isActive: true
  },

  // Airlines
  { 
    symbol: 'INDIGO', 
    instrumentToken: '10099201', 
    exchangeToken: '39468', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 48,
    name: 'InterGlobe Aviation Limited',
    sector: 'AIRLINES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2000000,
    marketCap: 180000,
    isActive: true
  },
  { 
    symbol: 'SPICEJET', 
    instrumentToken: '2236417', 
    exchangeToken: '8735', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 49,
    name: 'SpiceJet Limited',
    sector: 'AIRLINES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 8000,
    isActive: true
  },

  // E-commerce & Tech
  { 
    symbol: 'ZOMATO', 
    instrumentToken: '17007617', 
    exchangeToken: '66401', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 50,
    name: 'Zomato Limited',
    sector: 'TECH',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 35000000,
    marketCap: 220000,
    isActive: true
  },

  // Additional Pharma
  { 
    symbol: 'DIVISLAB', 
    instrumentToken: '2800641', 
    exchangeToken: '10939', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 51,
    name: 'Divis Laboratories Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1800000,
    marketCap: 140000,
    isActive: true
  },
  { 
    symbol: 'BIOCON', 
    instrumentToken: '11459', 
    exchangeToken: '11459', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 52,
    name: 'Biocon Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 6000000,
    marketCap: 35000,
    isActive: true
  },
  { 
    symbol: 'LUPIN', 
    instrumentToken: '522241', 
    exchangeToken: '2040', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 53,
    name: 'Lupin Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'AUROPHARMA', 
    instrumentToken: '70401', 
    exchangeToken: '275', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 54,
    name: 'Aurobindo Pharma Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4200000,
    marketCap: 75000,
    isActive: true
  },

  // Additional Metals
  { 
    symbol: 'COALINDIA', 
    instrumentToken: '5215745', 
    exchangeToken: '20374', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 55,
    name: 'Coal India Limited',
    sector: 'METALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 15000000,
    marketCap: 120000,
    isActive: true
  },
  { 
    symbol: 'VEDL', 
    instrumentToken: '784129', 
    exchangeToken: '3063', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 56,
    name: 'Vedanta Limited',
    sector: 'METALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 22000000,
    marketCap: 140000,
    isActive: true
  },
  { 
    symbol: 'SAIL', 
    instrumentToken: '758017', 
    exchangeToken: '2961', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 57,
    name: 'Steel Authority of India Limited',
    sector: 'METALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 35000000,
    marketCap: 45000,
    isActive: true
  },
  { 
    symbol: 'NMDC', 
    instrumentToken: '601857', 
    exchangeToken: '2351', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 58,
    name: 'NMDC Limited',
    sector: 'METALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 85000,
    isActive: true
  },

  // Additional Oil & Gas
  { 
    symbol: 'BPCL', 
    instrumentToken: '134657', 
    exchangeToken: '526', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 59,
    name: 'Bharat Petroleum Corporation Limited',
    sector: 'OIL_GAS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'GAIL', 
    instrumentToken: '1207553', 
    exchangeToken: '4717', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 60,
    name: 'GAIL (India) Limited',
    sector: 'OIL_GAS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 18000000,
    marketCap: 75000,
    isActive: true
  },

  // Additional Power
  { 
    symbol: 'ADANIPOWER', 
    instrumentToken: '4343041', 
    exchangeToken: '16969', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 61,
    name: 'Adani Power Limited',
    sector: 'POWER',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 85000000,
    marketCap: 220000,
    isActive: true
  },
  { 
    symbol: 'TATAPOWER', 
    instrumentToken: '877057', 
    exchangeToken: '3426', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 62,
    name: 'Tata Power Company Limited',
    sector: 'POWER',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 32000000,
    marketCap: 110000,
    isActive: true
  },

  // Additional Cement
  { 
    symbol: 'GRASIM', 
    instrumentToken: '315393', 
    exchangeToken: '1232', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 63,
    name: 'Grasim Industries Limited',
    sector: 'CEMENT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 140000,
    isActive: true
  },
  { 
    symbol: 'ACC', 
    instrumentToken: '5633', 
    exchangeToken: '22', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 64,
    name: 'ACC Limited',
    sector: 'CEMENT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2800000,
    marketCap: 65000,
    isActive: true
  },

  // Additional FMCG
  { 
    symbol: 'MARICO', 
    instrumentToken: '500010', 
    exchangeToken: '1953', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 65,
    name: 'Marico Limited',
    sector: 'FMCG',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4500000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'GODREJCP', 
    instrumentToken: '2904577', 
    exchangeToken: '11351', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 66,
    name: 'Godrej Consumer Products Limited',
    sector: 'FMCG',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3200000,
    marketCap: 120000,
    isActive: true
  },
  { 
    symbol: 'COLPAL', 
    instrumentToken: '5258753', 
    exchangeToken: '20542', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 67,
    name: 'Colgate-Palmolive (India) Limited',
    sector: 'FMCG',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 65000,
    isActive: true
  },

  // Additional Auto
  { 
    symbol: 'HEROMOTOCO', 
    instrumentToken: '345089', 
    exchangeToken: '1348', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 68,
    name: 'Hero MotoCorp Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2200000,
    marketCap: 110000,
    isActive: true
  },
  { 
    symbol: 'ASHOKLEY', 
    instrumentToken: '54273', 
    exchangeToken: '212', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 69,
    name: 'Ashok Leyland Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 15000000,
    marketCap: 65000,
    isActive: true
  },
  { 
    symbol: 'ESCORTS', 
    instrumentToken: '236033', 
    exchangeToken: '922', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 70,
    name: 'Escorts Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4500000,
    marketCap: 45000,
    isActive: true
  },

  // Additional IT
  { 
    symbol: 'LTI', 
    instrumentToken: '11483', 
    exchangeToken: '11483', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 71,
    name: 'Larsen & Toubro Infotech Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2000000,
    marketCap: 80000,
    isActive: true
  },
  { 
    symbol: 'MINDTREE', 
    instrumentToken: '3675137', 
    exchangeToken: '14356', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 72,
    name: 'Mindtree Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1800000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'MPHASIS', 
    instrumentToken: '2674433', 
    exchangeToken: '10444', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 73,
    name: 'Mphasis Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 65000,
    isActive: true
  },
  { 
    symbol: 'COFORGE', 
    instrumentToken: '1895937', 
    exchangeToken: '7407', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 74,
    name: 'Coforge Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 45000,
    isActive: true
  },

  // Additional Banking
  { 
    symbol: 'PNB', 
    instrumentToken: '1081345', 
    exchangeToken: '4226', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 75,
    name: 'Punjab National Bank',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 45000000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'BANKBARODA', 
    instrumentToken: '85761', 
    exchangeToken: '335', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 76,
    name: 'Bank of Baroda',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 35000000,
    marketCap: 75000,
    isActive: true
  },
  { 
    symbol: 'CANBK', 
    instrumentToken: '149249', 
    exchangeToken: '583', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 77,
    name: 'Canara Bank',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 28000000,
    marketCap: 65000,
    isActive: true
  },
  { 
    symbol: 'FEDERALBNK', 
    instrumentToken: '261889', 
    exchangeToken: '1023', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 78,
    name: 'Federal Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 22000000,
    marketCap: 35000,
    isActive: true
  },

  // Insurance
  { 
    symbol: 'SBILIFE', 
    instrumentToken: '15835649', 
    exchangeToken: '61851', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 79,
    name: 'SBI Life Insurance Company Limited',
    sector: 'INSURANCE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 120000,
    isActive: true
  },
  { 
    symbol: 'HDFCLIFE', 
    instrumentToken: '15268609', 
    exchangeToken: '59639', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 80,
    name: 'HDFC Life Insurance Company Limited',
    sector: 'INSURANCE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2800000,
    marketCap: 140000,
    isActive: true
  },
  { 
    symbol: 'ICICIPRULI', 
    instrumentToken: '5258497', 
    exchangeToken: '20541', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 81,
    name: 'ICICI Prudential Life Insurance Company Limited',
    sector: 'INSURANCE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2200000,
    marketCap: 95000,
    isActive: true
  },

  // Healthcare
  { 
    symbol: 'APOLLOHOSP', 
    instrumentToken: '52353', 
    exchangeToken: '204', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 82,
    name: 'Apollo Hospitals Enterprise Limited',
    sector: 'HEALTHCARE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1800000,
    marketCap: 110000,
    isActive: true
  },
  { 
    symbol: 'FORTIS', 
    instrumentToken: '2868225', 
    exchangeToken: '11208', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 83,
    name: 'Fortis Healthcare Limited',
    sector: 'HEALTHCARE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4500000,
    marketCap: 45000,
    isActive: true
  },

  // Real Estate
  { 
    symbol: 'DLF', 
    instrumentToken: '2129153', 
    exchangeToken: '8316', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 84,
    name: 'DLF Limited',
    sector: 'REAL_ESTATE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 15000000,
    marketCap: 185000,
    isActive: true
  },
  { 
    symbol: 'GODREJPROP', 
    instrumentToken: '2918401', 
    exchangeToken: '11399', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 85,
    name: 'Godrej Properties Limited',
    sector: 'REAL_ESTATE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3200000,
    marketCap: 95000,
    isActive: true
  },

  // Retail
  { 
    symbol: 'TRENT', 
    instrumentToken: '758529', 
    exchangeToken: '2963', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 86,
    name: 'Trent Limited',
    sector: 'RETAIL',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2800000,
    marketCap: 280000,
    isActive: true
  },
  { 
    symbol: 'DMART', 
    instrumentToken: '14977281', 
    exchangeToken: '58506', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 87,
    name: 'Avenue Supermarts Limited',
    sector: 'RETAIL',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 320000,
    isActive: true
  },

  // Additional NBFCs
  { 
    symbol: 'SHRIRAMFIN', 
    instrumentToken: '2664193', 
    exchangeToken: '10404', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 88,
    name: 'Shriram Finance Limited',
    sector: 'NBFC',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 6500000,
    marketCap: 140000,
    isActive: true
  },
  { 
    symbol: 'CHOLAFIN', 
    instrumentToken: '175361', 
    exchangeToken: '685', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 89,
    name: 'Cholamandalam Investment and Finance Company Limited',
    sector: 'NBFC',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4200000,
    marketCap: 85000,
    isActive: true
  },

  // Chemicals
  { 
    symbol: 'UPL', 
    instrumentToken: '2889473', 
    exchangeToken: '11287', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 90,
    name: 'UPL Limited',
    sector: 'CHEMICALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8500000,
    marketCap: 95000,
    isActive: true
  },
  { 
    symbol: 'PIDILITIND', 
    instrumentToken: '681985', 
    exchangeToken: '2664', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 91,
    name: 'Pidilite Industries Limited',
    sector: 'CHEMICALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1800000,
    marketCap: 140000,
    isActive: true
  },
  { 
    symbol: 'TATACHEM', 
    instrumentToken: '873217', 
    exchangeToken: '3410', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 92,
    name: 'Tata Chemicals Limited',
    sector: 'CHEMICALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 65000,
    isActive: true
  },

  // Media & Entertainment
  { 
    symbol: 'ZEEL', 
    instrumentToken: '975873', 
    exchangeToken: '3812', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 93,
    name: 'Zee Entertainment Enterprises Limited',
    sector: 'MEDIA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 35000,
    isActive: true
  },
  { 
    symbol: 'PVRINOX', 
    instrumentToken: '6191105', 
    exchangeToken: '24184', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 94,
    name: 'PVR INOX Limited',
    sector: 'MEDIA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2200000,
    marketCap: 25000,
    isActive: true
  },

  // Utilities
  { 
    symbol: 'IGL', 
    instrumentToken: '1846529', 
    exchangeToken: '7211', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 95,
    name: 'Indraprastha Gas Limited',
    sector: 'UTILITIES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 6500000,
    marketCap: 65000,
    isActive: true
  },
  { 
    symbol: 'MGL', 
    instrumentToken: '519425', 
    exchangeToken: '2029', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 96,
    name: 'Mahanagar Gas Limited',
    sector: 'UTILITIES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1800000,
    marketCap: 45000,
    isActive: true
  },

  // Additional Tech/E-commerce
  { 
    symbol: 'PAYTM', 
    instrumentToken: '18007297', 
    exchangeToken: '70313', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 97,
    name: 'One 97 Communications Limited',
    sector: 'TECH',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 28000000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'NYKAA', 
    instrumentToken: '24222465', 
    exchangeToken: '94615', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 98,
    name: 'FSN E-Commerce Ventures Limited',
    sector: 'TECH',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8500000,
    marketCap: 95000,
    isActive: true
  },

  // Defense & Railways
  { 
    symbol: 'HAL', 
    instrumentToken: '1355521', 
    exchangeToken: '5294', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 99,
    name: 'Hindustan Aeronautics Limited',
    sector: 'DEFENSE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4500000,
    marketCap: 280000,
    isActive: true
  },
  { 
    symbol: 'BEL', 
    instrumentToken: '113409', 
    exchangeToken: '443', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 100,
    name: 'Bharat Electronics Limited',
    sector: 'DEFENSE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 15000000,
    marketCap: 185000,
    isActive: true
  },
  { 
    symbol: 'IRCTC', 
    instrumentToken: '13894657', 
    exchangeToken: '54271', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 101,
    name: 'Indian Railway Catering and Tourism Corporation Limited',
    sector: 'RAILWAYS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8500000,
    marketCap: 95000,
    isActive: true
  },
  { 
    symbol: 'IRFC', 
    instrumentToken: '27125249', 
    exchangeToken: '105957', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 102,
    name: 'Indian Railway Finance Corporation Limited',
    sector: 'RAILWAYS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 45000000,
    marketCap: 180000,
    isActive: true
  },

  // Textiles
  { 
    symbol: 'ARVIND', 
    instrumentToken: '81729', 
    exchangeToken: '319', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 103,
    name: 'Arvind Limited',
    sector: 'TEXTILES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 25000,
    isActive: true
  },

  // Additional Consumer Goods
  { 
    symbol: 'BATA', 
    instrumentToken: '94977', 
    exchangeToken: '371', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 105,
    name: 'Bata India Limited',
    sector: 'CONSUMER_GOODS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 25000,
    isActive: true
  },
  { 
    symbol: 'RELAXO', 
    instrumentToken: '3930625', 
    exchangeToken: '15354', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 106,
    name: 'Relaxo Footwears Limited',
    sector: 'CONSUMER_GOODS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 35000,
    isActive: true
  },

  // Fertilizers & Agriculture
  { 
    symbol: 'RALLIS', 
    instrumentToken: '708609', 
    exchangeToken: '2768', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 107,
    name: 'Rallis India Limited',
    sector: 'AGRICULTURE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2200000,
    marketCap: 15000,
    isActive: true
  },
  { 
    symbol: 'COROMANDEL', 
    instrumentToken: '4749057', 
    exchangeToken: '18551', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 108,
    name: 'Coromandel International Limited',
    sector: 'AGRICULTURE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1800000,
    marketCap: 45000,
    isActive: true
  },

  // Renewable Energy
  { 
    symbol: 'ADANIGREEN', 
    instrumentToken: '15083265', 
    exchangeToken: '58906', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 109,
    name: 'Adani Green Energy Limited',
    sector: 'RENEWABLE_ENERGY',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 280000,
    isActive: true
  },
  { 
    symbol: 'SUZLON', 
    instrumentToken: '857857', 
    exchangeToken: '3351', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 110,
    name: 'Suzlon Energy Limited',
    sector: 'RENEWABLE_ENERGY',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 85000000,
    marketCap: 25000,
    isActive: true
  },

  // Logistics
  { 
    symbol: 'DELHIVERY', 
    instrumentToken: '24222721', 
    exchangeToken: '94616', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 111,
    name: 'Delhivery Limited',
    sector: 'LOGISTICS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8500000,
    marketCap: 65000,
    isActive: true
  },
  { 
    symbol: 'BLUEDART', 
    instrumentToken: '4464129', 
    exchangeToken: '17438', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 112,
    name: 'Blue Dart Express Limited',
    sector: 'LOGISTICS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 180000,
    marketCap: 35000,
    isActive: true
  },

  // Specialty Chemicals
  { 
    symbol: 'BALKRISIND', 
    instrumentToken: '90369', 
    exchangeToken: '353', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 113,
    name: 'Balkrishna Industries Limited',
    sector: 'CHEMICALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'AAVAS', 
    instrumentToken: '14559489', 
    exchangeToken: '56873', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 114,
    name: 'Aavas Financiers Limited',
    sector: 'NBFC',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 450000,
    marketCap: 25000,
    isActive: true
  },

  // Additional Infrastructure & PSU
  { 
    symbol: 'BHEL', 
    instrumentToken: '118529', 
    exchangeToken: '463', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 115,
    name: 'Bharat Heavy Electricals Limited',
    sector: 'INFRASTRUCTURE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 35000000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'CONCOR', 
    instrumentToken: '169729', 
    exchangeToken: '663', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 116,
    name: 'Container Corporation of India Limited',
    sector: 'LOGISTICS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 65000,
    isActive: true
  },
  { 
    symbol: 'ADANIPORTS', 
    instrumentToken: '15083521', 
    exchangeToken: '58907', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 117,
    name: 'Adani Ports and Special Economic Zone Limited',
    sector: 'INFRASTRUCTURE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 15000000,
    marketCap: 320000,
    isActive: true
  },

  // Additional Financial Services
  { 
    symbol: 'YESBANK', 
    instrumentToken: '397825', 
    exchangeToken: '1554', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 118,
    name: 'Yes Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 125000000,
    marketCap: 45000,
    isActive: true
  },
  { 
    symbol: 'RBLBANK', 
    instrumentToken: '5023745', 
    exchangeToken: '19625', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 119,
    name: 'RBL Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8500000,
    marketCap: 25000,
    isActive: true
  },
  { 
    symbol: 'IDFCFIRSTB', 
    instrumentToken: '10812033', 
    exchangeToken: '42249', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 120,
    name: 'IDFC First Bank Limited',
    sector: 'BANKING',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 22000000,
    marketCap: 65000,
    isActive: true
  },

  // Commodities & Mining
  { 
    symbol: 'MCX', 
    instrumentToken: '2885377', 
    exchangeToken: '11271', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 121,
    name: 'Multi Commodity Exchange of India Limited',
    sector: 'COMMODITIES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 45000,
    isActive: true
  },
  { 
    symbol: 'CDSL', 
    instrumentToken: '16154113', 
    exchangeToken: '63087', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 122,
    name: 'Central Depository Services (India) Limited',
    sector: 'FINANCIAL_SERVICES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 35000,
    isActive: true
  },

  // Additional Power
  { 
    symbol: 'NHPC', 
    instrumentToken: '590849', 
    exchangeToken: '2308', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 123,
    name: 'NHPC Limited',
    sector: 'POWER',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 45000000,
    marketCap: 185000,
    isActive: true
  },
  { 
    symbol: 'SJVN', 
    instrumentToken: '2914049', 
    exchangeToken: '11378', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 124,
    name: 'SJVN Limited',
    sector: 'POWER',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 28000000,
    marketCap: 85000,
    isActive: true
  },

  // Additional Tech Services
  { 
    symbol: 'PERSISTENT', 
    instrumentToken: '3020801', 
    exchangeToken: '11800', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 125,
    name: 'Persistent Systems Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'LTTS', 
    instrumentToken: '10447361', 
    exchangeToken: '40811', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 126,
    name: 'L&T Technology Services Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 120000,
    isActive: true
  },

  // Shipping & Marine
  { 
    symbol: 'COCHINSHIP', 
    instrumentToken: '172801', 
    exchangeToken: '675', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 127,
    name: 'Cochin Shipyard Limited',
    sector: 'DEFENSE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4500000,
    marketCap: 85000,
    isActive: true
  },
  { 
    symbol: 'MAZAGON', 
    instrumentToken: '10875649', 
    exchangeToken: '42483', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 128,
    name: 'Mazagon Dock Shipbuilders Limited',
    sector: 'DEFENSE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 120000,
    isActive: true
  },

  // Additional PSU Banks & Finance
  { 
    symbol: 'HUDCO', 
    instrumentToken: '7020289', 
    exchangeToken: '27423', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 129,
    name: 'Housing and Urban Development Corporation Limited',
    sector: 'FINANCIAL_SERVICES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 15000000,
    marketCap: 65000,
    isActive: true
  },
  { 
    symbol: 'RVNL', 
    instrumentToken: '889601', 
    exchangeToken: '3475', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 130,
    name: 'Rail Vikas Nigam Limited',
    sector: 'INFRASTRUCTURE',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 25000000,
    marketCap: 185000,
    isActive: true
  },

  // Additional Cement & Building Materials
  { 
    symbol: 'AMBUJACEMNT', 
    instrumentToken: '41729', 
    exchangeToken: '163', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 131,
    name: 'Ambuja Cements Limited',
    sector: 'CEMENT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8500000,
    marketCap: 140000,
    isActive: true
  },
  { 
    symbol: 'INDIACEM', 
    instrumentToken: '386049', 
    exchangeToken: '1508', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 132,
    name: 'The India Cements Limited',
    sector: 'CEMENT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 25000,
    isActive: true
  },

  // Additional Metals & Minerals
  { 
    symbol: 'HINDZINC', 
    instrumentToken: '360961', 
    exchangeToken: '1410', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 133,
    name: 'Hindustan Zinc Limited',
    sector: 'METALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 185000,
    isActive: true
  },
  { 
    symbol: 'MOIL', 
    instrumentToken: '269569', 
    exchangeToken: '1053', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 134,
    name: 'MOIL Limited',
    sector: 'METALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2200000,
    marketCap: 25000,
    isActive: true
  },

  // Additional Gas Utilities
  { 
    symbol: 'PETRONET', 
    instrumentToken: '2563329', 
    exchangeToken: '10018', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 135,
    name: 'Petronet LNG Limited',
    sector: 'OIL_GAS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 6500000,
    marketCap: 85000,
    isActive: true
  },

  // Additional Tech/Pharma
  { 
    symbol: 'JBCHEPHARM', 
    instrumentToken: '6191873', 
    exchangeToken: '24187', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 136,
    name: 'JB Chemicals & Pharmaceuticals Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 35000,
    isActive: true
  },
  { 
    symbol: 'TORNTPHARM', 
    instrumentToken: '685825', 
    exchangeToken: '2679', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 137,
    name: 'Torrent Pharmaceuticals Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 65000,
    isActive: true
  },

  // Additional Financial Services
  { 
    symbol: 'JIOFINANCE', 
    instrumentToken: '25847041', 
    exchangeToken: '101031', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 138,
    name: 'Jio Financial Services Limited',
    sector: 'FINANCIAL_SERVICES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 45000000,
    marketCap: 220000,
    isActive: true
  },
  { 
    symbol: 'POLICYBZR', 
    instrumentToken: '22688769', 
    exchangeToken: '88628', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 139,
    name: 'PB Fintech Limited',
    sector: 'TECH',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 4500000,
    marketCap: 85000,
    isActive: true
  },

  // Electric Vehicles & Future Mobility
  { 
    symbol: 'MAHINDCIE', 
    instrumentToken: '2815745', 
    exchangeToken: '10999', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 140,
    name: 'Mahindra CIE Automotive Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 25000,
    isActive: true
  },

  // Renewable & Clean Energy
  { 
    symbol: 'GREENPANEL', 
    instrumentToken: '2995457', 
    exchangeToken: '11703', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 141,
    name: 'Greenply Industries Limited',
    sector: 'BUILDING_MATERIALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 800000,
    marketCap: 15000,
    isActive: true
  },

  // Additional IT & Software Services
  { 
    symbol: 'LTIM', 
    instrumentToken: '25754369', 
    exchangeToken: '100603', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 142,
    name: 'LTIMindtree Limited',
    sector: 'IT',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 2200000,
    marketCap: 180000,
    isActive: true
  },

  // Additional Consumer Discretionary
  { 
    symbol: 'FORCEMOT', 
    instrumentToken: '543489', 
    exchangeToken: '2123', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 143,
    name: 'Force Motors Limited',
    sector: 'AUTO',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 1200000,
    marketCap: 25000,
    isActive: true
  },

  // Additional Specialty Stocks
  { 
    symbol: 'ADANIENT', 
    instrumentToken: '23558401', 
    exchangeToken: '92001', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 144,
    name: 'Adani Enterprises Limited',
    sector: 'DIVERSIFIED',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 8500000,
    marketCap: 350000,
    isActive: true
  },

  // Final Additional Banking
  { 
    symbol: 'IDFC', 
    instrumentToken: '384001', 
    exchangeToken: '1500', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 145,
    name: 'IDFC Limited',
    sector: 'FINANCIAL_SERVICES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 12000000,
    marketCap: 45000,
    isActive: true
  },

  // Final High-Volume PSU Stock
  { 
    symbol: 'RECLTD', 
    instrumentToken: '722689', 
    exchangeToken: '2823', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 146,
    name: 'REC Limited',
    sector: 'FINANCIAL_SERVICES',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 25000000,
    marketCap: 140000,
    isActive: true
  },

  // Final Pharma/Healthcare
  { 
    symbol: 'GLENMARK', 
    instrumentToken: '304897', 
    exchangeToken: '1191', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 147,
    name: 'Glenmark Pharmaceuticals Limited',
    sector: 'PHARMA',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 3500000,
    marketCap: 35000,
    isActive: true
  },

  // Final Specialty Chemical
  { 
    symbol: 'ATUL', 
    instrumentToken: '70913', 
    exchangeToken: '277', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 148,
    name: 'Atul Limited',
    sector: 'CHEMICALS',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 280000,
    marketCap: 45000,
    isActive: true
  },

  // Final High-Priority Stock - 149th Stock
  { 
    symbol: 'IREDA', 
    instrumentToken: '26404353', 
    exchangeToken: '103142', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 149,
    name: 'Indian Renewable Energy Development Agency Limited',
    sector: 'RENEWABLE_ENERGY',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 15000000,
    marketCap: 95000,
    isActive: true
  },

  // 150th and Final Stock - High Volume Trading
  { 
    symbol: 'VODAFONE', 
    instrumentToken: '783361', 
    exchangeToken: '3060', 
    exchange: 'NSE', 
    segment: 'EQ', 
    type: 'EQ', 
    priority: 150,
    name: 'Vodafone Idea Limited',
    sector: 'TELECOM',
    lotSize: 1,
    tickSize: 0.05,
    avgVolume: 285000000,
    marketCap: 85000,
    isActive: true
  }
];

export const STOCK_CATEGORIES = {
  INDICES: ['NIFTY 50', 'NIFTY BANK', 'SENSEX', 'NIFTY IT', 'NIFTY AUTO'],
  BANKING: ['HDFCBANK', 'ICICIBANK', 'KOTAKBANK', 'SBIN', 'AXISBANK', 'INDUSINDBK', 'BANDHANBNK', 'PNB', 'BANKBARODA', 'CANBK', 'FEDERALBNK', 'YESBANK', 'RBLBANK', 'IDFCFIRSTB'],
  IT: ['TCS', 'INFY', 'WIPRO', 'HCLTECH', 'TECHM', 'LTI', 'MINDTREE', 'MPHASIS', 'COFORGE', 'PERSISTENT', 'LTTS', 'LTIM'],
  FMCG: ['HINDUNILVR', 'ITC', 'NESTLEIND', 'BRITANNIA', 'DABUR', 'MARICO', 'GODREJCP', 'COLPAL'],
  AUTO: ['MARUTI', 'TATAMOTORS', 'M&M', 'BAJAJ-AUTO', 'EICHERMOT', 'HEROMOTOCO', 'ASHOKLEY', 'ESCORTS', 'FORCEMOT'],
  PHARMA: ['SUNPHARMA', 'DRREDDY', 'CIPLA', 'DIVISLAB', 'BIOCON', 'LUPIN', 'AUROPHARMA', 'JBCHEPHARM', 'TORNTPHARM', 'GLENMARK'],
  METALS: ['TATASTEEL', 'JSWSTEEL', 'HINDALCO', 'COALINDIA', 'VEDL', 'SAIL', 'NMDC', 'HINDZINC', 'MOIL'],
  ENERGY: ['RELIANCE', 'BHARTIARTL'],
  OIL_GAS: ['ONGC', 'IOC', 'BPCL', 'GAIL', 'PETRONET'],
  POWER: ['POWERGRID', 'NTPC', 'ADANIPOWER', 'TATAPOWER', 'NHPC', 'SJVN'],
  CEMENT: ['ULTRACEMCO', 'SHREECEM', 'GRASIM', 'ACC', 'AMBUJACEMNT', 'INDIACEM'],
  INFRASTRUCTURE: ['LT', 'SIEMENS', 'BHEL', 'ADANIPORTS', 'RVNL'],
  NBFC: ['BAJFINANCE', 'BAJAJFINSV', 'SHRIRAMFIN', 'CHOLAFIN', 'AAVAS'],
  CONSUMER_GOODS: ['TITAN', 'ASIANPAINT', 'BATA', 'RELAXO'],
  AIRLINES: ['INDIGO', 'SPICEJET'],
  TECH: ['ZOMATO', 'PAYTM', 'NYKAA', 'POLICYBZR'],
  INSURANCE: ['SBILIFE', 'HDFCLIFE', 'ICICIPRULI'],
  HEALTHCARE: ['APOLLOHOSP', 'FORTIS'],
  REAL_ESTATE: ['DLF', 'GODREJPROP'],
  RETAIL: ['TRENT', 'DMART'],
  CHEMICALS: ['UPL', 'PIDILITIND', 'TATACHEM', 'BALKRISIND', 'ATUL'],
  MEDIA: ['ZEEL', 'PVRINOX'],
  UTILITIES: ['IGL', 'MGL'],
  DEFENSE: ['HAL', 'BEL', 'COCHINSHIP', 'MAZAGON'],
  RAILWAYS: ['IRCTC', 'IRFC'],
  TEXTILES: ['ARVIND'],
  AGRICULTURE: ['RALLIS', 'COROMANDEL'],
  RENEWABLE_ENERGY: ['ADANIGREEN', 'SUZLON'],
  LOGISTICS: ['DELHIVERY', 'BLUEDART', 'CONCOR'],
  COMMODITIES: ['MCX'],
  FINANCIAL_SERVICES: ['CDSL', 'HUDCO', 'JIOFINANCE', 'IDFC', 'RECLTD'],
  BUILDING_MATERIALS: ['GREENPANEL'],
  DIVERSIFIED: ['ADANIENT'],
  TELECOM: ['VODAFONE']
};

// Helper function to get stocks by category
export const getStocksByCategory = (category: string): IStockData[] => {
  const symbols = STOCK_CATEGORIES[category as keyof typeof STOCK_CATEGORIES] || [];
  return IMPORTANT_STOCKS.filter(stock => symbols.includes(stock.symbol));
};

// Helper function to get top priority stocks
export const getTopPriorityStocks = (limit: number = 20): IStockData[] => {
  return IMPORTANT_STOCKS
    .sort((a, b) => a.priority - b.priority)
    .slice(0, limit);
};

// Helper function to get active stocks only
export const getActiveStocks = (): IStockData[] => {
  return IMPORTANT_STOCKS.filter(stock => stock.isActive === true);
};

// Helper function to get stocks by exchange
export const getStocksByExchange = (exchange: string): IStockData[] => {
  return IMPORTANT_STOCKS.filter(stock => stock.exchange === exchange);
};

// Helper function to get stocks by segment
export const getStocksBySegment = (segment: string): IStockData[] => {
  return IMPORTANT_STOCKS.filter(stock => stock.segment === segment);
};
